### ISSUE TITLE
make branch name optional

### ISSUE THREAD

**Issue by jonatanpedersen** [debitoor/tcmerge#3]
it seems redundant to have to write the branch name as argument to tcmerge, it should at least just take the current branch if none is specified.

``` bash
debitoor-bob (make-bob-great-again-for-developers) $ tcmerge
```

instead of

``` bash
debitoor-bob (make-bob-great-again-for-developers) $ tcmerge make-bob-great-again-for-developers
```

**Comment by ebdrup** [comment]
Expensive lesson I learned why this in maybe not the best idea. You can accidentally deploy something you did not mean to deploy. So it's totally on purpose with this "sanity check".
